# config/cucumber.yml
##YAML Template

android: PLATFORM=android --exclude features/ios

ios: PLATFORM=ios --exclude features/android

bruno: QA=bruno -f json -o reports/report.json

murilo: QA=murilo

jenkins: QA=jenkins -f json -o reports/report.json