# config/cucumber.yml
##YAML Template

android: PLATFORM=android --exclude features/iOS

ios: PLATFORM=ios --exclude features/Android

bruno: QA=bruno #-f html -o reports/report.html

murilo: QA=murilo

jenkins: QA=jenkins -f json -o reports/report.json